# Generated by Django 3.0.3 on 2020-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200307_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
