# Generated by Django 3.0.3 on 2020-03-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='profile_img/default.png', upload_to='profile_img'),
        ),
    ]
