# Generated by Django 3.0.3 on 2020-03-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
