# Generated by Django 3.0.3 on 2020-03-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
