# Generated by Django 3.0.3 on 2020-03-08 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_relativo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='lugar',
            new_name='departamento',
        ),
        migrations.DeleteModel(
            name='ubication',
        ),
        migrations.AddField(
            model_name='municipio',
            name='ubication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubication.departamento'),
        ),
    ]
