# Generated by Django 2.0.2 on 2020-03-09 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proucts',
            new_name='products',
        ),
    ]
