# Generated by Django 3.0.3 on 2020-03-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_store_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_location',
        ),
    ]
