# Generated by Django 3.0.3 on 2020-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_delete_imagexstore'),
        ('store', '0007_auto_20200312_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_images',
            field=models.ManyToManyField(related_name='get_images_store', to='images.Image'),
        ),
    ]
