# Generated by Django 3.0.3 on 2020-03-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_store_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersxstore',
            options={'verbose_name': 'Usuario por Tienda', 'verbose_name_plural': 'Usuarios por Tiendas'},
        ),
    ]
