# Generated by Django 3.0.3 on 2020-03-12 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('direction', models.CharField(default='Ninguna', max_length=50, primary_key=True, serialize=False)),
                ('correlative_direction', models.ForeignKey(blank=True, default='Ninguna', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
    ]
