# Generated by Django 3.0.3 on 2020-03-10 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('ad', '0004_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Uniti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniti_tipe', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Add_Kind',
            new_name='Ad_Kind',
        ),
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.AddField(
            model_name='ad',
            name='id_ad_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Ad_Kind'),
        ),
        migrations.AddField(
            model_name='ad',
            name='id_categori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Categories'),
        ),
        migrations.AddField(
            model_name='ad',
            name='id_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AddField(
            model_name='ad',
            name='id_ubication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Ubication'),
        ),
        migrations.AddField(
            model_name='ad',
            name='id_uniti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Uniti'),
        ),
        migrations.AddField(
            model_name='ad',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
