# Generated by Django 3.0.3 on 2020-03-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20200310_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad_kind',
            old_name='add_kind',
            new_name='ad_kind',
        ),
    ]
