# Generated by Django 3.0.3 on 2020-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_auto_20200310_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniti',
            name='uniti_tipe',
            field=models.CharField(default='Unidad', max_length=10),
        ),
    ]
