# Generated by Django 3.0.3 on 2020-03-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_auto_20200310_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad_Kind',
            new_name='AdKind',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Ubication',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Uniti',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='id_categori',
            new_name='id_category',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='id_ubication',
            new_name='id_location',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='id_uniti',
            new_name='id_unit',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categori_description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categori_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='uniti_tipe',
            new_name='unit_type',
        ),
    ]
