# Generated by Django 3.0.3 on 2020-03-12 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('ad', '0008_auto_20200311_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='adkind',
            options={'verbose_name': 'Tipo de Anuncio', 'verbose_name_plural': 'Tipos de Anuncio'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='id_store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Unit'),
        ),
    ]
