# Generated by Django 3.0.3 on 2020-03-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0010_ad_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon_class',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
