# Generated by Django 3.0.3 on 2020-03-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_category_category_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon_class',
            field=models.CharField(max_length=100),
        ),
    ]
