# Generated by Django 3.0.3 on 2020-03-12 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0013_currency_pricerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_equals', models.FloatField()),
                ('currency_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_one', to='ad.Currency')),
                ('currency_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_two', to='ad.Currency')),
            ],
            options={
                'verbose_name': 'Conversión de Moneda',
                'verbose_name_plural': 'Conversiones de Moneda',
            },
        ),
    ]
