# Generated by Django 3.0.3 on 2020-03-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0015_auto_20200311_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='id_user',
            new_name='iduser',
        ),
    ]
