# Generated by Django 3.0.3 on 2020-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_delete_imagexad'),
        ('ad', '0017_auto_20200315_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_images',
            field=models.ManyToManyField(related_name='get_images', to='images.Image', verbose_name='Imagenes del anuncio'),
        ),
    ]
