# Generated by Django 3.0.3 on 2020-03-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_delete_imagexad'),
        ('ad', '0019_auto_20200316_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_images',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_images',
            field=models.ManyToManyField(related_name='get_images', to='images.Image'),
        ),
    ]
