# Generated by Django 3.0.3 on 2020-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_delete_imagexstore'),
        ('ad', '0020_auto_20200316_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_images',
            field=models.ManyToManyField(related_name='get_images_ad', to='images.Image'),
        ),
    ]
