# Generated by Django 3.0.3 on 2020-03-11 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_route', models.ImageField(upload_to='Ad_Images', verbose_name='Ruta de la Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_route', models.ImageField(upload_to='User_Images', verbose_name='Ruta de la Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='ImageXAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_img', to='images.AdImg', verbose_name='Ruta de la Imagen')),
                ('img_ad_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_ad_owner', to='images.AdImg', verbose_name='Publicacion a la que pertenece la imagen')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesXUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_user_owner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario al que pertenece la imagen')),
                ('user_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_img', to='images.UserImage', verbose_name='Ruta de la Imagen')),
            ],
        ),
    ]
