# Generated by Django 3.0.3 on 2020-03-11 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('images', '0002_auto_20200310_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_route', models.ImageField(upload_to='Images', verbose_name='Ruta de la Imagen')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='ImageXStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_img', to='images.Image', verbose_name='Ruta de la Imagen')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_store_owner', to='store.Store', verbose_name='Tienda a la que pertenece la imagen')),
            ],
            options={
                'verbose_name': 'Imagen por anuncio',
                'verbose_name_plural': 'Imagenes por Anuncio',
            },
        ),
        migrations.CreateModel(
            name='ImageXUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_img', to='images.Image', verbose_name='Ruta de la Imagen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_user_owner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario al que pertenece la imagen')),
            ],
            options={
                'verbose_name': 'Imagen por usuario',
                'verbose_name_plural': 'Imagenes por Usuario',
            },
        ),
        migrations.RemoveField(
            model_name='imagesxuser',
            name='img_user_owner',
        ),
        migrations.RemoveField(
            model_name='imagesxuser',
            name='user_img',
        ),
        migrations.AlterModelOptions(
            name='imagexad',
            options={'verbose_name': 'Imagen por anuncio', 'verbose_name_plural': 'Imagenes por Anuncio'},
        ),
        migrations.RenameField(
            model_name='imagexad',
            old_name='img_ad_owner',
            new_name='ad',
        ),
        migrations.RemoveField(
            model_name='imagexad',
            name='ad_img',
        ),
        migrations.DeleteModel(
            name='AdImg',
        ),
        migrations.DeleteModel(
            name='ImagesXUser',
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
        migrations.AddField(
            model_name='imagexad',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ad_img', to='images.Image', verbose_name='Ruta de la Imagen'),
            preserve_default=False,
        ),
    ]
