# Generated by Django 3.0.3 on 2020-03-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200311_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagexad',
            options={'verbose_name': 'Imagen por Anuncio', 'verbose_name_plural': 'Imagenes por Anuncio'},
        ),
        migrations.AlterModelOptions(
            name='imagexstore',
            options={'verbose_name': 'Imagen por Tienda', 'verbose_name_plural': 'Imagenes por Tienda'},
        ),
        migrations.AlterModelOptions(
            name='imagexuser',
            options={'verbose_name': 'Imagen por Usuario', 'verbose_name_plural': 'Imagenes por Usuario'},
        ),
    ]
