# Generated by Django 3.0.3 on 2020-03-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_remove_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageXAd',
        ),
    ]
