# Generated by Django 3.0.3 on 2020-03-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_delete_imagexad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageXStore',
        ),
    ]
