# Generated by Django 3.0.3 on 2020-03-16 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0008_delete_imagexstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagexuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_user_owner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario al que pertenece imagen'),
        ),
    ]
